import type { Metadata } from "next"; // Keep metadata import in this Server Component
import localFont from "next/font/local";
import Script from "next/script";
import "./globals.css";
import CartProvider from "./components/Providers";
import LayoutWrapper from "./components/LayoutWrapper";
import { CurrencyProvider } from "./context/CurrencyContext";
import { ThemeProvider } from "./context/ThemeContext";
import { CompareProvider } from "./context/CompareContext";
import { WishlistProvider } from "./context/WishlistContext";
import { UserInteractionProvider } from "./context/UserInteractionContext";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Define metadata as a Server Component
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <Script
          src="https://www.googletagmanager.com/gtag/js?id=G-TEST123456"
          strategy="afterInteractive"
        />
        <Script id="google-analytics" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-TEST123456');
          `}
        </Script>
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ThemeProvider>
          <CurrencyProvider>
            <CompareProvider>
              <WishlistProvider>
                <UserInteractionProvider>
                  <CartProvider>
                    <LayoutWrapper>
                      {children}
                    </LayoutWrapper>
                  </CartProvider>
                </UserInteractionProvider>
              </WishlistProvider>
            </CompareProvider>
          </CurrencyProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
