import type { Metadata } from "next"; // Keep metadata import in this Server Component
import localFont from "next/font/local";
import "./globals.css";
import CartProvider from "./components/Providers";
import LayoutWrapper from "./components/LayoutWrapper";
import { CurrencyProvider } from "./context/CurrencyContext";
import { ThemeProvider } from "./context/ThemeContext";
import { CompareProvider } from "./context/CompareContext";
import { WishlistProvider } from "./context/WishlistContext";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Define metadata as a Server Component
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ThemeProvider>
          <CurrencyProvider>
            <CompareProvider>
              <WishlistProvider>
                <CartProvider>
                  <LayoutWrapper>
                    {children}
                  </LayoutWrapper>
                </CartProvider>
              </WishlistProvider>
            </CompareProvider>
          </CurrencyProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
