import type { Metadata } from "next"; // Keep metadata import in this Server Component
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/Navbar";
import CartProvider from "./components/Providers";
import React from "react"; // Remove useState import
import Footer from "./components/Footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Define metadata as a Server Component
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <CartProvider>
          <Navbar /> {/* Pass the function to open modal */}
          {children} {/* Renders the content of each page */}
         <Footer/>
        </CartProvider>
      </body>
    </html>
  );
}
